name: MiniWorld2
version: '${project.version}'
main: me.radcriminal77.miniworld2.MiniWorld2
api-version: 1.19
authors:
  - TheKDub
  - RadCriminal77
commands:
  CreateEmptyWorld:
    usage: /<command> name