name: MakeMyWorldUnique
version: '${project.version}'
main: com.decinco.makemyworldunique.UniqueMain
api-version: 1.21
load: STARTUP # load is on startup because worlds might use MiniWorld2:empty as their generators for void worlds
authors:
  - TheKDub
  - RadCriminal77
depend:
  - Multiverse-Core
softdepend:
  - WorldGuard
commands:
  CreateVoidWorld:
    description: A helper command to create void worlds
    usage: /<command> world-name
    permission: MiniWorld2.CreateVoidWorld
  CreateMiniature:
    description: Creates a miniature (a temporary clone) of the provided world
    usage: /<command> parent-world
    permission: MiniWorld2.CreateMiniature
  RemoveMiniature:
    description: Deletes a miniature world
    usage: /<command> miniature-world-name
    permission: MiniWorld2.RemoveMiniature
permissions:
  MiniWorld2.CreateVoidWorld:
    description: Allows you to use the command /CreateVoidWorld
  MiniWorld2.CreateMiniature:
    description: Allows you to use the command /CreateMiniature
  MiniWorld2.RemoveMiniature:
    description: Allows you tu use the command /RemoveMiniature