name: MiniWorld2
version: '${project.version}'
main: me.radcriminal77.miniworld2.MiniWorld2
api-version: 1.19
load: STARTUP # load is on startup because worlds might use MiniWorld2:empty as their generators for void worlds
authors:
  - TheKDub
  - RadCriminal77
depend:
  - Multiverse-Core
softdepend:
  - WorldGuard
commands:
  CreateVoidWorld:
    description: A helper command to create void worlds
    usage: /<command> world-name
  CreateMiniature:
    description: Creates a miniature (a temporary clone) of the provided world
    usage: /<command> parent-world
  RemoveMiniature:
    description: Deletes a miniature world
    usage: /<command> miniature-world-name