name: MiniWorld2
version: '${project.version}'
main: me.radcriminal77.miniworld2.MiniWorld2
api-version: 1.19
authors:
  - TheKDub
  - RadCriminal77
commands:
  CreateVoidWorld:
    description: A helper command to create void worlds
    usage: /<command> world-name
  CreateMiniature:
    description: Creates a miniature (a temporary clone) of the provided world
    usage: /<command> parent-world
depend:
  - Multiverse-Core